inherit_from: configs/pointcloud/room_grid_attention_encoder.yaml
data:
  input_type: pointcloud_crop
  classes: null
  path: /home/xxf/convolutional_occupancy_networks/data/demo/myself_processed
  pointcloud_n: 1000000
  pointcloud_noise: 0.0
  points_file: null
  points_iou_file: null
  pointcloud_file: pointcloud.npz
  pointcloud_chamfer_file: null
  boundary: null
  boundary_file: null
  multi_files: null
  voxels_file: null
  unit_size: 0.05 
  query_vol_size: 45 
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_type: 'grid'
    grid_resolution: 64
    unet3d: True
    unet3d_kwargs:
      num_levels: 4
      f_maps: 32
      in_channels: 32
      out_channels: 32
      is_unet: true
  decoder: simple_local #simple_local_transformer_knn10 #simple_local
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  c_dim: 32
training:
  out_dir: /data3/xxf/GridFormer/out/pointcloud/room_grid_attention_encoder
  batch_size: 8 #32 #9 #24 #10 #32
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 100000 #10000 #5000 #10000
  validate_every: 5 #5000 #5000 #5000 #10000
  checkpoint_every: 2
  backup_every: 10
  n_workers: 8
  n_workers_val: 4
  stage_1_epoch: 1600
  stage_2_epoch: 300
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  generation_dir: generation
  sliding_window: true # generate mesh in the sliding-window manner
  resolution_0: 64 # resolution for each crop
  upsampling_steps: 0
