method: conv_onet
data:
  input_type: pointcloud
  classes: null
  path: /data3/xxf/dataset/ShapeNet
  pointcloud_n: 3000 # 300
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: points.npz
  points_iou_file: points.npz
  boundary: boundary0.08 # 边界点的定义
  boundary_file: boundary_points.npz
  voxels_file: null
model:
  encoder: FKAConvEncoder2d #编码器pointnet_local_pool
  encoder_kwargs: #编码器的超参数
    hidden_dim: 32 #隐藏层的维数
    plane_type: ['xz', 'xy', 'yz'] #3平面
    plane_resolution: 64 #平面分辨率
    unet: True #使用U-net结构
    unet_kwargs:
      depth: 4 #网络深度
      merge_mode: concat
      start_filts: 32 #起始卷积的通道数
  # decoder: simple_local #解码器
  decoder: ulto_decoder
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest #采样模式
    hidden_size: 32
  c_dim: 32 #编码器输出的特征维度
training:
  out_dir: /data2/xxf/GridFormer/out/pointcloud/shapenet_3plane_attention_FKAConvEncoder_3000_n0.005_IID/
  batch_size: 16
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 10
  validate_every: 10
  checkpoint_every: 2
  backup_every: 10
  n_workers: 8
  n_workers_val: 4
  stage_1_epoch: 1500
  stage_2_epoch: 200
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  generation_dir: generation
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
